# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29242dcb6d6d6f697c399442cc44d66c5273ea6a49499a6c8a5872ae882e3c12bc0b304501a5308cb60ec58db5743246cdfa9a440459fe1dd218197c3f4e65e7

test:
  secret_key_base: 5bd6849090ad61315b3ada8d867c59b35344dbfc34f6d1a6ae822d45c87cfa8fefd8e5287847cb259b139f10667ce83548237469f8f090fe6cc68b0ff8579792

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
